# ==========================================================
# Solar PV Designer Pro Africa™
# PDF Report Module
# Version 2.0
# ==========================================================


# ==========================================================
# SECTION 1 - IMPORTS
# ==========================================================

from io import BytesIO
from datetime import date

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet


# ==========================================================
# SECTION 2 - PDF REPORT GENERATOR
# ==========================================================

def create_pdf_report(data, recommendations):
    """
    Generate a professional solar PV design report.

    Parameters:
        data:
            Dictionary containing project and
            engineering results.

        recommendations:
            List generated by the AI Solar Advisor.

    Returns:
        PDF file stored in memory.
    """


    buffer = BytesIO()


    document = SimpleDocTemplate(
        buffer
    )


    styles = getSampleStyleSheet()


    content = []


    # ======================================================
    # SECTION 3 - REPORT TITLE
    # ======================================================

    content.append(
        Paragraph(
            "Solar PV Designer Pro Africa™",
            styles["Title"]
        )
    )


    content.append(
        Paragraph(
            "Renewable Energy System Design Report",
            styles["Heading2"]
        )
    )


    content.append(
        Spacer(1, 15)
    )


    content.append(
        Paragraph(
            "Prepared by: "
            "Engr. Prof. Ibrahim Sani Madugu",
            styles["Normal"]
        )
    )


    content.append(
        Paragraph(
            f"Report Date: {date.today()}",
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1, 20)
    )


    # ======================================================
    # SECTION 4 - PROJECT SUMMARY
    # ======================================================

    content.append(
        Paragraph(
            "1. Project Summary",
            styles["Heading2"]
        )
    )


    summary = [

        ["Parameter", "Value"],

        [
            "Location",
            data["location"]
        ],

        [
            "Daily Energy Demand",
            f'{data["energy"]:.2f} kWh/day'
        ],

        [
            "Peak Sun Hours",
            f'{data["sun_hours"]:.2f} hours/day'
        ],

        [
            "Average Temperature",
            f'{data["temperature"]:.1f} °C'
        ],

        [
            "Battery Technology",
            data["battery_type"]
        ],

        [
            "Battery Autonomy",
            f'{data["days"]} days'
        ]

    ]


    summary_table = Table(
        summary
    )


    summary_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, None),

                ("BACKGROUND", (0, 0), (-1, 0), None),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("VALIGN", (0, 0), (-1, -1), "TOP")
            ]
        )
    )


    content.append(
        summary_table
    )


    content.append(
        Spacer(1, 20)
    )


    # ======================================================
    # SECTION 5 - TECHNICAL DESIGN
    # ======================================================

    content.append(
        Paragraph(
            "2. Technical Design Results",
            styles["Heading2"]
        )
    )


    technical = [

        ["Design Parameter", "Result"],

        [
            "PV Capacity",
            f'{data["pv"]:.2f} kW'
        ],

        [
            "Solar Panel Quantity",
            f'{data["panels"]} × {data["panel_rating"]} W'
        ],

        [
            "Battery Capacity",
            f'{data["battery"]:.2f} kWh'
        ],

        [
            "Inverter Size",
            f'{data["inverter"]:.2f} kW'
        ],

        [
            "Charge Controller",
            f'{data["controller"]:.1f} A'
        ]

    ]


    technical_table = Table(
        technical
    )


    technical_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, None),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("VALIGN", (0, 0), (-1, -1), "TOP")
            ]
        )
    )


    content.append(
        technical_table
    )


    content.append(
        Spacer(1, 20)
    )


    # ======================================================
    # SECTION 6 - ECONOMIC ANALYSIS
    # ======================================================

    content.append(
        Paragraph(
            "3. Economic Analysis",
            styles["Heading2"]
        )
    )


    economic = [

        ["Cost Component", "Estimated Cost"],

        [
            "PV Array",
            f'${data["panel_cost"]:,.0f}'
        ],

        [
            "Battery",
            f'${data["battery_cost"]:,.0f}'
        ],

        [
            "Inverter",
            f'${data["inverter_cost"]:,.0f}'
        ],

        [
            "Installation",
            f'${data["installation_cost"]:,.0f}'
        ],

        [
            "Total Estimated Cost",
            f'${data["cost"]:,.0f}'
        ]

    ]


    economic_table = Table(
        economic
    )


    economic_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, None),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold")
            ]
        )
    )


    content.append(
        economic_table
    )


    content.append(
        Spacer(1, 20)
    )


    # ======================================================
    # SECTION 7 - ENVIRONMENTAL IMPACT
    # ======================================================

    content.append(
        Paragraph(
            "4. Environmental Impact",
            styles["Heading2"]
        )
    )


    content.append(
        Paragraph(
            f'Estimated annual CO₂ reduction: '
            f'{data["carbon"]:,.0f} kg/year.',
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1, 20)
    )


    # ======================================================
    # SECTION 8 - AI SOLAR ADVISOR
    # ======================================================

    content.append(
        Paragraph(
            "5. AI Solar Advisor Recommendations",
            styles["Heading2"]
        )
    )


    for recommendation in recommendations:

        content.append(
            Paragraph(
                "• " + recommendation,
                styles["Normal"]
            )
        )

        content.append(
            Spacer(1, 6)
        )


    content.append(
        Spacer(1, 15)
    )


    # ======================================================
    # SECTION 9 - ENGINEERING DISCLAIMER
    # ======================================================

    content.append(
        Paragraph(
            "6. Engineering Disclaimer",
            styles["Heading2"]
        )
    )


    content.append(
        Paragraph(
            "This report provides preliminary engineering "
            "design guidance. Final equipment selection, "
            "electrical protection, cable sizing, structural "
            "design, battery safety and installation must be "
            "verified by a qualified professional and "
            "applicable local standards before implementation.",
            styles["Normal"]
        )
    )


    # ======================================================
    # SECTION 10 - BUILD PDF
    # ======================================================

    document.build(
        content
    )


    buffer.seek(0)


    return buffer
